# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/portfolio_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:022001}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Configuration
server.port=${PORT:9090}

# JWT Configuration
jwt.secret=${JWT_SECRET:9414a61124e8aa530679236c2e865429320a3f16a893239fecb7ddfbea1ad7c6}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Brevo (Sendinblue) Configuration
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL:baban.pandua@gmail.com}

# Cloudinary Configuration
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:deetjvqo0}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Contact Form Configuration
contact.target.email=${CONTACT_TARGET_EMAIL:gdebanshu1727@gmail.com}
